package com.fit2cloud.netty.model;

import java.io.Serializable;
import java.util.Date;

public class Plugin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.id
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.name
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.description
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.version
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.updated
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.owner
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.state
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.plugin_type
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private String pluginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.support_userdata
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private Boolean supportUserdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.support_password
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private Boolean supportPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.support_key
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private Boolean supportKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.support_create_server
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private Boolean supportCreateServer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.cloud_type
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private String cloudType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.id
     *
     * @return the value of plugin.id
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.id
     *
     * @param id the value for plugin.id
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.name
     *
     * @return the value of plugin.name
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.name
     *
     * @param name the value for plugin.name
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.description
     *
     * @return the value of plugin.description
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.description
     *
     * @param description the value for plugin.description
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.version
     *
     * @return the value of plugin.version
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.version
     *
     * @param version the value for plugin.version
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.updated
     *
     * @return the value of plugin.updated
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.updated
     *
     * @param updated the value for plugin.updated
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.owner
     *
     * @return the value of plugin.owner
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.owner
     *
     * @param owner the value for plugin.owner
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.state
     *
     * @return the value of plugin.state
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.state
     *
     * @param state the value for plugin.state
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.plugin_type
     *
     * @return the value of plugin.plugin_type
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public String getPluginType() {
        return pluginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.plugin_type
     *
     * @param pluginType the value for plugin.plugin_type
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setPluginType(String pluginType) {
        this.pluginType = pluginType == null ? null : pluginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.support_userdata
     *
     * @return the value of plugin.support_userdata
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public Boolean getSupportUserdata() {
        return supportUserdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.support_userdata
     *
     * @param supportUserdata the value for plugin.support_userdata
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setSupportUserdata(Boolean supportUserdata) {
        this.supportUserdata = supportUserdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.support_password
     *
     * @return the value of plugin.support_password
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public Boolean getSupportPassword() {
        return supportPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.support_password
     *
     * @param supportPassword the value for plugin.support_password
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setSupportPassword(Boolean supportPassword) {
        this.supportPassword = supportPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.support_key
     *
     * @return the value of plugin.support_key
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public Boolean getSupportKey() {
        return supportKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.support_key
     *
     * @param supportKey the value for plugin.support_key
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setSupportKey(Boolean supportKey) {
        this.supportKey = supportKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.support_create_server
     *
     * @return the value of plugin.support_create_server
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public Boolean getSupportCreateServer() {
        return supportCreateServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.support_create_server
     *
     * @param supportCreateServer the value for plugin.support_create_server
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setSupportCreateServer(Boolean supportCreateServer) {
        this.supportCreateServer = supportCreateServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.cloud_type
     *
     * @return the value of plugin.cloud_type
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public String getCloudType() {
        return cloudType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.cloud_type
     *
     * @param cloudType the value for plugin.cloud_type
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setCloudType(String cloudType) {
        this.cloudType = cloudType == null ? null : cloudType.trim();
    }
}