package com.fit2cloud.netty.model;

import java.io.Serializable;

public class PluginWithBLOBs extends Plugin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.current_file
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private String currentFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.icon
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.current_file
     *
     * @return the value of plugin.current_file
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public String getCurrentFile() {
        return currentFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.current_file
     *
     * @param currentFile the value for plugin.current_file
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setCurrentFile(String currentFile) {
        this.currentFile = currentFile == null ? null : currentFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.icon
     *
     * @return the value of plugin.icon
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.icon
     *
     * @param icon the value for plugin.icon
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}