package com.fit2cloud.netty.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PluginExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public PluginExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("updated is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("updated is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("updated =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("updated <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("updated >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("updated >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("updated <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("updated <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("updated in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("updated not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("updated between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("updated not between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("owner is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("owner is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(String value) {
            addCriterion("owner =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(String value) {
            addCriterion("owner <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(String value) {
            addCriterion("owner >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("owner >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(String value) {
            addCriterion("owner <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(String value) {
            addCriterion("owner <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLike(String value) {
            addCriterion("owner like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotLike(String value) {
            addCriterion("owner not like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<String> values) {
            addCriterion("owner in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<String> values) {
            addCriterion("owner not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(String value1, String value2) {
            addCriterion("owner between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(String value1, String value2) {
            addCriterion("owner not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andPluginTypeIsNull() {
            addCriterion("plugin_type is null");
            return (Criteria) this;
        }

        public Criteria andPluginTypeIsNotNull() {
            addCriterion("plugin_type is not null");
            return (Criteria) this;
        }

        public Criteria andPluginTypeEqualTo(String value) {
            addCriterion("plugin_type =", value, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeNotEqualTo(String value) {
            addCriterion("plugin_type <>", value, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeGreaterThan(String value) {
            addCriterion("plugin_type >", value, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeGreaterThanOrEqualTo(String value) {
            addCriterion("plugin_type >=", value, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeLessThan(String value) {
            addCriterion("plugin_type <", value, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeLessThanOrEqualTo(String value) {
            addCriterion("plugin_type <=", value, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeLike(String value) {
            addCriterion("plugin_type like", value, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeNotLike(String value) {
            addCriterion("plugin_type not like", value, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeIn(List<String> values) {
            addCriterion("plugin_type in", values, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeNotIn(List<String> values) {
            addCriterion("plugin_type not in", values, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeBetween(String value1, String value2) {
            addCriterion("plugin_type between", value1, value2, "pluginType");
            return (Criteria) this;
        }

        public Criteria andPluginTypeNotBetween(String value1, String value2) {
            addCriterion("plugin_type not between", value1, value2, "pluginType");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataIsNull() {
            addCriterion("support_userdata is null");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataIsNotNull() {
            addCriterion("support_userdata is not null");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataEqualTo(Boolean value) {
            addCriterion("support_userdata =", value, "supportUserdata");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataNotEqualTo(Boolean value) {
            addCriterion("support_userdata <>", value, "supportUserdata");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataGreaterThan(Boolean value) {
            addCriterion("support_userdata >", value, "supportUserdata");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataGreaterThanOrEqualTo(Boolean value) {
            addCriterion("support_userdata >=", value, "supportUserdata");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataLessThan(Boolean value) {
            addCriterion("support_userdata <", value, "supportUserdata");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataLessThanOrEqualTo(Boolean value) {
            addCriterion("support_userdata <=", value, "supportUserdata");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataIn(List<Boolean> values) {
            addCriterion("support_userdata in", values, "supportUserdata");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataNotIn(List<Boolean> values) {
            addCriterion("support_userdata not in", values, "supportUserdata");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataBetween(Boolean value1, Boolean value2) {
            addCriterion("support_userdata between", value1, value2, "supportUserdata");
            return (Criteria) this;
        }

        public Criteria andSupportUserdataNotBetween(Boolean value1, Boolean value2) {
            addCriterion("support_userdata not between", value1, value2, "supportUserdata");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordIsNull() {
            addCriterion("support_password is null");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordIsNotNull() {
            addCriterion("support_password is not null");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordEqualTo(Boolean value) {
            addCriterion("support_password =", value, "supportPassword");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordNotEqualTo(Boolean value) {
            addCriterion("support_password <>", value, "supportPassword");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordGreaterThan(Boolean value) {
            addCriterion("support_password >", value, "supportPassword");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordGreaterThanOrEqualTo(Boolean value) {
            addCriterion("support_password >=", value, "supportPassword");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordLessThan(Boolean value) {
            addCriterion("support_password <", value, "supportPassword");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordLessThanOrEqualTo(Boolean value) {
            addCriterion("support_password <=", value, "supportPassword");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordIn(List<Boolean> values) {
            addCriterion("support_password in", values, "supportPassword");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordNotIn(List<Boolean> values) {
            addCriterion("support_password not in", values, "supportPassword");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordBetween(Boolean value1, Boolean value2) {
            addCriterion("support_password between", value1, value2, "supportPassword");
            return (Criteria) this;
        }

        public Criteria andSupportPasswordNotBetween(Boolean value1, Boolean value2) {
            addCriterion("support_password not between", value1, value2, "supportPassword");
            return (Criteria) this;
        }

        public Criteria andSupportKeyIsNull() {
            addCriterion("support_key is null");
            return (Criteria) this;
        }

        public Criteria andSupportKeyIsNotNull() {
            addCriterion("support_key is not null");
            return (Criteria) this;
        }

        public Criteria andSupportKeyEqualTo(Boolean value) {
            addCriterion("support_key =", value, "supportKey");
            return (Criteria) this;
        }

        public Criteria andSupportKeyNotEqualTo(Boolean value) {
            addCriterion("support_key <>", value, "supportKey");
            return (Criteria) this;
        }

        public Criteria andSupportKeyGreaterThan(Boolean value) {
            addCriterion("support_key >", value, "supportKey");
            return (Criteria) this;
        }

        public Criteria andSupportKeyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("support_key >=", value, "supportKey");
            return (Criteria) this;
        }

        public Criteria andSupportKeyLessThan(Boolean value) {
            addCriterion("support_key <", value, "supportKey");
            return (Criteria) this;
        }

        public Criteria andSupportKeyLessThanOrEqualTo(Boolean value) {
            addCriterion("support_key <=", value, "supportKey");
            return (Criteria) this;
        }

        public Criteria andSupportKeyIn(List<Boolean> values) {
            addCriterion("support_key in", values, "supportKey");
            return (Criteria) this;
        }

        public Criteria andSupportKeyNotIn(List<Boolean> values) {
            addCriterion("support_key not in", values, "supportKey");
            return (Criteria) this;
        }

        public Criteria andSupportKeyBetween(Boolean value1, Boolean value2) {
            addCriterion("support_key between", value1, value2, "supportKey");
            return (Criteria) this;
        }

        public Criteria andSupportKeyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("support_key not between", value1, value2, "supportKey");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerIsNull() {
            addCriterion("support_create_server is null");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerIsNotNull() {
            addCriterion("support_create_server is not null");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerEqualTo(Boolean value) {
            addCriterion("support_create_server =", value, "supportCreateServer");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerNotEqualTo(Boolean value) {
            addCriterion("support_create_server <>", value, "supportCreateServer");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerGreaterThan(Boolean value) {
            addCriterion("support_create_server >", value, "supportCreateServer");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerGreaterThanOrEqualTo(Boolean value) {
            addCriterion("support_create_server >=", value, "supportCreateServer");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerLessThan(Boolean value) {
            addCriterion("support_create_server <", value, "supportCreateServer");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerLessThanOrEqualTo(Boolean value) {
            addCriterion("support_create_server <=", value, "supportCreateServer");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerIn(List<Boolean> values) {
            addCriterion("support_create_server in", values, "supportCreateServer");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerNotIn(List<Boolean> values) {
            addCriterion("support_create_server not in", values, "supportCreateServer");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerBetween(Boolean value1, Boolean value2) {
            addCriterion("support_create_server between", value1, value2, "supportCreateServer");
            return (Criteria) this;
        }

        public Criteria andSupportCreateServerNotBetween(Boolean value1, Boolean value2) {
            addCriterion("support_create_server not between", value1, value2, "supportCreateServer");
            return (Criteria) this;
        }

        public Criteria andCloudTypeIsNull() {
            addCriterion("cloud_type is null");
            return (Criteria) this;
        }

        public Criteria andCloudTypeIsNotNull() {
            addCriterion("cloud_type is not null");
            return (Criteria) this;
        }

        public Criteria andCloudTypeEqualTo(String value) {
            addCriterion("cloud_type =", value, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeNotEqualTo(String value) {
            addCriterion("cloud_type <>", value, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeGreaterThan(String value) {
            addCriterion("cloud_type >", value, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeGreaterThanOrEqualTo(String value) {
            addCriterion("cloud_type >=", value, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeLessThan(String value) {
            addCriterion("cloud_type <", value, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeLessThanOrEqualTo(String value) {
            addCriterion("cloud_type <=", value, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeLike(String value) {
            addCriterion("cloud_type like", value, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeNotLike(String value) {
            addCriterion("cloud_type not like", value, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeIn(List<String> values) {
            addCriterion("cloud_type in", values, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeNotIn(List<String> values) {
            addCriterion("cloud_type not in", values, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeBetween(String value1, String value2) {
            addCriterion("cloud_type between", value1, value2, "cloudType");
            return (Criteria) this;
        }

        public Criteria andCloudTypeNotBetween(String value1, String value2) {
            addCriterion("cloud_type not between", value1, value2, "cloudType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plugin
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 19 11:26:11 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}