package com.fit2cloud.netty.model;

import lombok.Data;

import java.io.Serializable;

@Data
public class Tag implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.server_id
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private Long serverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.group_id
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.name
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.value
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.cluster_id
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private Long clusterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.cluster_role_id
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private Long clusterRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.server_name
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private String serverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.cluster_name
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private String clusterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.cluster_role_name
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private String clusterRoleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag
     *
     * @mbg.generated Sun Mar 17 20:10:01 CST 2019
     */
    private static final long serialVersionUID = 1L;
}