package com.fit2cloud.netty.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.source
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.access_token
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.admin
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private Boolean admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private Long phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.active_code
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String activeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.active_timeout
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private Date activeTimeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.forget_code
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String forgetCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.forget_timeout
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private Date forgetTimeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_login
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.description
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ldap_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String ldapId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.staff_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_mode
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private String lastMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.current_group_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private Long currentGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cost_center_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private Long costCenterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.source
     *
     * @return the value of user.source
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.source
     *
     * @param source the value for user.source
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.access_token
     *
     * @return the value of user.access_token
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.access_token
     *
     * @param accessToken the value for user.access_token
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created
     *
     * @return the value of user.created
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created
     *
     * @param created the value for user.created
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.admin
     *
     * @return the value of user.admin
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public Boolean getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.admin
     *
     * @param admin the value for user.admin
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company
     *
     * @return the value of user.company
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company
     *
     * @param company the value for user.company
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public Long getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.active_code
     *
     * @return the value of user.active_code
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getActiveCode() {
        return activeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.active_code
     *
     * @param activeCode the value for user.active_code
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setActiveCode(String activeCode) {
        this.activeCode = activeCode == null ? null : activeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.active_timeout
     *
     * @return the value of user.active_timeout
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public Date getActiveTimeout() {
        return activeTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.active_timeout
     *
     * @param activeTimeout the value for user.active_timeout
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setActiveTimeout(Date activeTimeout) {
        this.activeTimeout = activeTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.forget_code
     *
     * @return the value of user.forget_code
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getForgetCode() {
        return forgetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.forget_code
     *
     * @param forgetCode the value for user.forget_code
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setForgetCode(String forgetCode) {
        this.forgetCode = forgetCode == null ? null : forgetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.forget_timeout
     *
     * @return the value of user.forget_timeout
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public Date getForgetTimeout() {
        return forgetTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.forget_timeout
     *
     * @param forgetTimeout the value for user.forget_timeout
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setForgetTimeout(Date forgetTimeout) {
        this.forgetTimeout = forgetTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_login
     *
     * @return the value of user.last_login
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_login
     *
     * @param lastLogin the value for user.last_login
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.description
     *
     * @return the value of user.description
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.description
     *
     * @param description the value for user.description
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ldap_id
     *
     * @return the value of user.ldap_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getLdapId() {
        return ldapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ldap_id
     *
     * @param ldapId the value for user.ldap_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setLdapId(String ldapId) {
        this.ldapId = ldapId == null ? null : ldapId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.staff_id
     *
     * @return the value of user.staff_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.staff_id
     *
     * @param staffId the value for user.staff_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_mode
     *
     * @return the value of user.last_mode
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public String getLastMode() {
        return lastMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_mode
     *
     * @param lastMode the value for user.last_mode
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setLastMode(String lastMode) {
        this.lastMode = lastMode == null ? null : lastMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.current_group_id
     *
     * @return the value of user.current_group_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public Long getCurrentGroupId() {
        return currentGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.current_group_id
     *
     * @param currentGroupId the value for user.current_group_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setCurrentGroupId(Long currentGroupId) {
        this.currentGroupId = currentGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cost_center_id
     *
     * @return the value of user.cost_center_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public Long getCostCenterId() {
        return costCenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cost_center_id
     *
     * @param costCenterId the value for user.cost_center_id
     *
     * @mbg.generated Wed Aug 15 15:49:33 CST 2018
     */
    public void setCostCenterId(Long costCenterId) {
        this.costCenterId = costCenterId;
    }
}