package com.fit2cloud.netty.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.source
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.access_token
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.admin
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private Boolean admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private Long phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.active_code
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String activeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.active_timeout
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private Date activeTimeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.forget_code
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String forgetCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.forget_timeout
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private Date forgetTimeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_login
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.description
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ldap_id
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String ldapId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.staff_id
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_mode
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private String lastMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.current_group_id
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private Long currentGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cost_center_id
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private Long costCenterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sun Mar 17 20:11:12 CST 2019
     */
    private static final long serialVersionUID = 1L;
}