package com.fit2cloud.netty.dao;

import com.fit2cloud.netty.model.Plugin;
import com.fit2cloud.netty.model.PluginExample;
import com.fit2cloud.netty.model.PluginWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PluginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    long countByExample(PluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    int deleteByExample(PluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    int insert(PluginWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    int insertSelective(PluginWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    List<PluginWithBLOBs> selectByExampleWithBLOBs(PluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    List<Plugin> selectByExample(PluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    PluginWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") PluginWithBLOBs record, @Param("example") PluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") PluginWithBLOBs record, @Param("example") PluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    int updateByExample(@Param("record") Plugin record, @Param("example") PluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    int updateByPrimaryKeySelective(PluginWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PluginWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated Sun Aug 19 11:26:11 CST 2018
     */
    int updateByPrimaryKey(Plugin record);
}